import org.gradle.kotlin.dsl.support.unzipTo

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.6.2/userguide/java_library_plugin.html
 */

plugins {
    // Apply the java-library plugin to add support for Java Library
    `java-library`
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()

    flatDir {
        dirs("libs")
    }

    ivy {
        url = uri("http://download.forge.ow2.org/sat4j")
        patternLayout {
            artifact("sat4j-[module].[ext]")
        }
    }

}

dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api("org.apache.commons:commons-math3:3.6.1")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation("com.google.guava:guava:28.0-jre")
    implementation("javax.xml.bind:jaxb-api:2.2.11")
    implementation("com.sun.xml.bind:jaxb-core:2.2.11")
    implementation("com.sun.xml.bind:jaxb-impl:2.2.11")
    implementation("javax.activation:activation:1.1.1")

    // Use JUnit test framework
    testImplementation("junit:junit:4.12")

    compile ("sat4j:1.7")
    compile ("org.deckfour.xes:OpenXES:2.26")
}

application {
    mainClassName = "dfa_identification.Main"
}
